name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  # job's id
  release:
    runs-on: ubuntu-latest
    name: release rma4go bininaries
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
          workdir: .
        env:
          GITHUB_TOKEN: ${{ GEN_TOKEN }}
